vim.keymap.set("n", "<space>w", "<C-w>", { desc = "Window mode" })
vim.keymap.set("n", [[\]], function()
	vim.cmd("noh")
end, { desc = "Remove highlight" })
vim.keymap.set("t", "<esc><esc>", "<C-\\><C-n>C-w>")
